// Individual survey records used by the per-campaign Recent Surveys list
// and the Survey Detail page. Each survey carries:
//   Q1 — rating (1–5) for the dominant interaction topic
//   Q2 — AI-generated open text from interaction topic + sentiment
//   Q3 — AI-generated open text from Q2's response sentiment

export type SurveyStatus = 'completed' | 'partial' | 'abandoned' | 'pending'

export type RatingQuestion = {
  kind: 'rating'
  prompt: string
  topic: string
  min: 1
  max: 5
  response: number | null
}

export type OpenQuestion = {
  kind: 'open'
  prompt: string
  topic: string
  // What primed the AI to generate this question
  generatedFrom: { source: 'interaction' | 'prior-response'; sentiment: number; topic?: string }
  response: string | null
  responseSentiment: number | null
}

export type SurveyQuestion = RatingQuestion | OpenQuestion

export type Survey = {
  id: string
  campaignId: string
  customer: { name: string; phone: string; email: string }
  agent: { name: string; id: string }
  interaction: {
    date: string
    channel: string
    durationMinutes: number
    topicsDetected: string[]
    sentiment: number
    summary: string
  }
  surveySentAt: string
  surveyCompletedAt: string | null
  status: SurveyStatus
  csat: number | null
  vu: number
  questions: SurveyQuestion[]
}

export const SURVEYS: Survey[] = [
  /* ============================================================
   * Flight Disruption Recovery
   * ============================================================ */
  {
    id: 'SR-FDR-001',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'Emma Wright', phone: '+44 7700 900 142', email: 'emma.wright@example.com' },
    agent: { name: 'Priya M.', id: 'AG-2241' },
    interaction: {
      date: '2026-05-29T10:14:00Z',
      channel: 'AI Agent',
      durationMinutes: 9,
      topicsDetected: ['Flight Disruption', 'Rebooking'],
      sentiment: 12,
      summary: 'Customer rebooked onto the next-day flight smoothly via AI Agent. No friction reported.',
    },
    surveySentAt: '2026-05-29T13:00:00Z',
    surveyCompletedAt: '2026-05-29T13:18:00Z',
    status: 'completed',
    csat: 100,
    vu: 36,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate the rebooking experience after your disruption?',
        topic: 'Rebooking',
        min: 1, max: 5,
        response: 5,
      },
      {
        kind: 'open',
        prompt: 'What worked well for you during the rebooking process?',
        topic: 'Rebooking',
        generatedFrom: { source: 'interaction', sentiment: 12, topic: 'Rebooking' },
        response: 'The bot pulled up my booking instantly and offered me three flights to pick from. Took under five minutes.',
        responseSentiment: 28,
      },
      {
        kind: 'open',
        prompt: 'Is there anything we should keep doing for future disruptions?',
        topic: 'Rebooking',
        generatedFrom: { source: 'prior-response', sentiment: 28 },
        response: 'Honestly the speed. Most airlines I would still be on hold.',
        responseSentiment: 34,
      },
    ],
  },
  {
    id: 'SR-FDR-002',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'Marcus Chen', phone: '+44 7700 900 318', email: 'm.chen@example.com' },
    agent: { name: 'Priya M.', id: 'AG-2241' },
    interaction: {
      date: '2026-05-31T08:42:00Z',
      channel: 'AI Agent',
      durationMinutes: 14,
      topicsDetected: ['Flight Disruption', 'Rebooking'],
      sentiment: -22,
      summary: 'Customer rebooked onto a later flight. Reported repeated booking-reference entry due to a session timeout.',
    },
    surveySentAt: '2026-05-31T12:00:00Z',
    surveyCompletedAt: '2026-05-31T12:11:00Z',
    status: 'completed',
    csat: 80,
    vu: 39,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate the rebooking experience?',
        topic: 'Rebooking',
        min: 1, max: 5,
        response: 4,
      },
      {
        kind: 'open',
        prompt: 'What made the experience feel difficult?',
        topic: 'Rebooking',
        generatedFrom: { source: 'interaction', sentiment: -22, topic: 'Rebooking' },
        response: 'The agent was helpful but the rebooking system kept timing out and I had to repeat my details twice.',
        responseSentiment: -18,
      },
      {
        kind: 'open',
        prompt: 'What would have made it smoother for you?',
        topic: 'Rebooking',
        generatedFrom: { source: 'prior-response', sentiment: -18 },
        response: 'If the system saved my context between transfers I wouldn\'t have had to repeat my booking ref.',
        responseSentiment: -8,
      },
    ],
  },
  {
    id: 'SR-FDR-003',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'Sophie Williams', phone: '+44 7700 900 502', email: 'sophie.w@example.com' },
    agent: { name: 'Ben K.', id: 'AG-2189' },
    interaction: {
      date: '2026-05-30T15:20:00Z',
      channel: 'Chat',
      durationMinutes: 22,
      topicsDetected: ['Flight Disruption', 'Compensation'],
      sentiment: -48,
      summary: 'Customer disputed the compensation offered after a 6-hour delay. Conversation escalated mid-chat.',
    },
    surveySentAt: '2026-05-30T20:00:00Z',
    surveyCompletedAt: '2026-05-30T20:25:00Z',
    status: 'completed',
    csat: 40,
    vu: 47,
    questions: [
      {
        kind: 'rating',
        prompt: 'How fairly were you compensated for the disruption?',
        topic: 'Compensation',
        min: 1, max: 5,
        response: 2,
      },
      {
        kind: 'open',
        prompt: 'What about the compensation offer felt unfair?',
        topic: 'Compensation',
        generatedFrom: { source: 'interaction', sentiment: -48, topic: 'Compensation' },
        response: 'I was offered a £10 food voucher for a 6 hour delay. My connecting flight was missed and I had to book a hotel out of pocket. The voucher does not even begin to cover that.',
        responseSentiment: -62,
      },
      {
        kind: 'open',
        prompt: 'What level of compensation would have felt fair to you in this situation?',
        topic: 'Compensation',
        generatedFrom: { source: 'prior-response', sentiment: -62 },
        response: 'At minimum reimbursement of the hotel and the meal cost. The voucher feels insulting given what it actually cost me.',
        responseSentiment: -44,
      },
    ],
  },
  {
    id: 'SR-FDR-004',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'Hassan Al-Farsi', phone: '+971 50 234 8821', email: 'h.alfarsi@example.com' },
    agent: { name: 'Liu Yang', id: 'AG-2310' },
    interaction: {
      date: '2026-05-28T18:55:00Z',
      channel: 'AI Agent',
      durationMinutes: 11,
      topicsDetected: ['Flight Disruption', 'Communication During Disruption'],
      sentiment: -8,
      summary: 'Customer asked for clearer status updates on the delay. Routed through AI Agent and resolved.',
    },
    surveySentAt: '2026-05-28T22:00:00Z',
    surveyCompletedAt: '2026-05-28T22:14:00Z',
    status: 'completed',
    csat: 80,
    vu: 33,
    questions: [
      {
        kind: 'rating',
        prompt: 'How clear were the updates we sent you during the disruption?',
        topic: 'Communication During Disruption',
        min: 1, max: 5,
        response: 4,
      },
      {
        kind: 'open',
        prompt: 'What information would have helped you most during the delay?',
        topic: 'Communication During Disruption',
        generatedFrom: { source: 'interaction', sentiment: -8, topic: 'Communication During Disruption' },
        response: 'I wanted to know the actual new departure time, not just that it was delayed. The push notifications kept saying delayed without an updated time.',
        responseSentiment: -14,
      },
      {
        kind: 'open',
        prompt: 'Where in the journey would that information have been most useful?',
        topic: 'Communication During Disruption',
        generatedFrom: { source: 'prior-response', sentiment: -14 },
        response: 'At the gate. By the time the screens updated everyone was already crowding the desk.',
        responseSentiment: -10,
      },
    ],
  },
  {
    id: 'SR-FDR-005',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'Olivia Brown', phone: '+44 7700 900 088', email: 'olivia.brown@example.com' },
    agent: { name: 'Rajat S.', id: 'AG-2208' },
    interaction: {
      date: '2026-05-31T14:08:00Z',
      channel: 'AI Agent',
      durationMinutes: 7,
      topicsDetected: ['Flight Disruption', 'Refund Processing'],
      sentiment: -4,
      summary: 'Customer requested refund after cancellation. AI Agent processed; customer received refund timeline.',
    },
    surveySentAt: '2026-05-31T18:00:00Z',
    surveyCompletedAt: null,
    status: 'partial',
    csat: 60,
    vu: 31,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate the refund process so far?',
        topic: 'Refund Processing',
        min: 1, max: 5,
        response: 3,
      },
      {
        kind: 'open',
        prompt: 'What concerns do you still have about your refund?',
        topic: 'Refund Processing',
        generatedFrom: { source: 'interaction', sentiment: -4, topic: 'Refund Processing' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'How would you prefer to be kept updated on the refund status?',
        topic: 'Refund Processing',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
  {
    id: 'SR-FDR-006',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'James Taylor', phone: '+44 7700 900 916', email: 'j.taylor@example.com' },
    agent: { name: 'Ben K.', id: 'AG-2189' },
    interaction: {
      date: '2026-06-01T09:32:00Z',
      channel: 'Chat',
      durationMinutes: 18,
      topicsDetected: ['Flight Disruption', 'Baggage Claim'],
      sentiment: -36,
      summary: 'Customer combined a disruption complaint with a missing-bag issue. Routed to baggage team mid-chat.',
    },
    surveySentAt: '2026-06-01T16:00:00Z',
    surveyCompletedAt: null,
    status: 'abandoned',
    csat: null,
    vu: 44,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate how we handled your disruption and bag issue together?',
        topic: 'Flight Disruption',
        min: 1, max: 5,
        response: null,
      },
      {
        kind: 'open',
        prompt: 'What about that combined experience frustrated you most?',
        topic: 'Flight Disruption',
        generatedFrom: { source: 'interaction', sentiment: -36, topic: 'Flight Disruption' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'How could the handoff between disruption and baggage teams have felt smoother?',
        topic: 'Flight Disruption',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
  {
    id: 'SR-FDR-007',
    campaignId: 'flight-disruption-recovery',
    customer: { name: 'Aisha Patel', phone: '+44 7700 900 271', email: 'aisha.patel@example.com' },
    agent: { name: 'Liu Yang', id: 'AG-2310' },
    interaction: {
      date: '2026-05-30T21:10:00Z',
      channel: 'Chat',
      durationMinutes: 32,
      topicsDetected: ['Flight Disruption', 'Rebooking', 'Compensation'],
      sentiment: -64,
      summary: 'Customer stranded overnight. Multiple rebooking attempts failed. Compensation request not resolved in chat.',
    },
    surveySentAt: '2026-05-31T07:00:00Z',
    surveyCompletedAt: '2026-05-31T07:24:00Z',
    status: 'completed',
    csat: 20,
    vu: 52,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate how we handled your disruption overall?',
        topic: 'Flight Disruption',
        min: 1, max: 5,
        response: 1,
      },
      {
        kind: 'open',
        prompt: 'Walk us through the worst moment of the experience for you.',
        topic: 'Flight Disruption',
        generatedFrom: { source: 'interaction', sentiment: -64, topic: 'Flight Disruption' },
        response: 'I was stuck at the airport for 9 hours with my two kids. Every agent I spoke to passed me to someone else. By midnight no one would even commit to whether we had a flight the next day.',
        responseSentiment: -72,
      },
      {
        kind: 'open',
        prompt: 'What would have changed your experience that night?',
        topic: 'Flight Disruption',
        generatedFrom: { source: 'prior-response', sentiment: -72 },
        response: 'Honest answers. If you cannot rebook me just tell me. Do not keep me on hold pretending to look.',
        responseSentiment: -54,
      },
    ],
  },

  /* ============================================================
   * Baggage Claim Follow-up
   * ============================================================ */
  {
    id: 'SR-BCF-001',
    campaignId: 'baggage-claim-followup',
    customer: { name: 'Nadia Hassan', phone: '+44 7700 900 433', email: 'n.hassan@example.com' },
    agent: { name: 'Maya O.', id: 'AG-3104' },
    interaction: {
      date: '2026-05-28T11:00:00Z',
      channel: 'AI Agent',
      durationMinutes: 6,
      topicsDetected: ['Baggage Claim', 'Delivery Timeline'],
      sentiment: 8,
      summary: 'Customer reported a missing bag. AI Agent confirmed bag was tagged on next flight; delivered to her hotel.',
    },
    surveySentAt: '2026-05-29T18:00:00Z',
    surveyCompletedAt: '2026-05-29T18:09:00Z',
    status: 'completed',
    csat: 100,
    vu: 32,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate how quickly we got your bag back to you?',
        topic: 'Delivery Timeline',
        min: 1, max: 5,
        response: 5,
      },
      {
        kind: 'open',
        prompt: 'What worked well about the way we kept you informed?',
        topic: 'Delivery Timeline',
        generatedFrom: { source: 'interaction', sentiment: 8, topic: 'Delivery Timeline' },
        response: 'I got a text the moment the bag was found and another when it landed. No chasing required.',
        responseSentiment: 30,
      },
      {
        kind: 'open',
        prompt: 'Is there anything we should keep doing for other passengers?',
        topic: 'Delivery Timeline',
        generatedFrom: { source: 'prior-response', sentiment: 30 },
        response: 'Just the proactive texts. Felt looked after.',
        responseSentiment: 40,
      },
    ],
  },
  {
    id: 'SR-BCF-002',
    campaignId: 'baggage-claim-followup',
    customer: { name: 'Robert Klein', phone: '+49 151 234 8821', email: 'r.klein@example.com' },
    agent: { name: 'Tom H.', id: 'AG-3082' },
    interaction: {
      date: '2026-05-29T16:20:00Z',
      channel: 'Chat',
      durationMinutes: 12,
      topicsDetected: ['Baggage Claim', 'Lost Item'],
      sentiment: -14,
      summary: 'Bag found but took three days to be returned. Customer noted the wait was the main issue.',
    },
    surveySentAt: '2026-05-30T19:00:00Z',
    surveyCompletedAt: '2026-05-30T19:33:00Z',
    status: 'completed',
    csat: 60,
    vu: 35,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate the time it took to return your bag?',
        topic: 'Delivery Timeline',
        min: 1, max: 5,
        response: 3,
      },
      {
        kind: 'open',
        prompt: 'What about the three-day wait felt longest for you?',
        topic: 'Delivery Timeline',
        generatedFrom: { source: 'interaction', sentiment: -14, topic: 'Delivery Timeline' },
        response: 'The first 36 hours where I had no update at all. I didn\'t know if it had even been found.',
        responseSentiment: -20,
      },
      {
        kind: 'open',
        prompt: 'What kind of update during that silent window would have helped?',
        topic: 'Delivery Timeline',
        generatedFrom: { source: 'prior-response', sentiment: -20 },
        response: 'Even a generic "we have located it, it is in transit" message would have helped. Not knowing was the worst part.',
        responseSentiment: -12,
      },
    ],
  },
  {
    id: 'SR-BCF-003',
    campaignId: 'baggage-claim-followup',
    customer: { name: 'Yuki Tanaka', phone: '+81 90 1234 5678', email: 'y.tanaka@example.com' },
    agent: { name: 'Sara N.', id: 'AG-3151' },
    interaction: {
      date: '2026-05-30T08:10:00Z',
      channel: 'AI Agent',
      durationMinutes: 5,
      topicsDetected: ['Baggage Claim'],
      sentiment: 4,
      summary: 'Customer asked about claim status. AI Agent confirmed bag arrived and would be delivered the same day.',
    },
    surveySentAt: '2026-05-30T21:00:00Z',
    surveyCompletedAt: '2026-05-30T21:08:00Z',
    status: 'completed',
    csat: 80,
    vu: 30,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate the baggage claim process overall?',
        topic: 'Baggage Claim',
        min: 1, max: 5,
        response: 4,
      },
      {
        kind: 'open',
        prompt: 'What did you find easy about the process?',
        topic: 'Baggage Claim',
        generatedFrom: { source: 'interaction', sentiment: 4, topic: 'Baggage Claim' },
        response: 'The status check was painless. I asked the bot and got a clear answer in under a minute.',
        responseSentiment: 22,
      },
      {
        kind: 'open',
        prompt: 'Anything that would make it even better next time?',
        topic: 'Baggage Claim',
        generatedFrom: { source: 'prior-response', sentiment: 22 },
        response: 'A photo of the bag at the warehouse would be reassuring.',
        responseSentiment: 12,
      },
    ],
  },
  {
    id: 'SR-BCF-004',
    campaignId: 'baggage-claim-followup',
    customer: { name: 'Diego Martinez', phone: '+34 612 345 678', email: 'd.martinez@example.com' },
    agent: { name: 'Maya O.', id: 'AG-3104' },
    interaction: {
      date: '2026-05-31T13:45:00Z',
      channel: 'Chat',
      durationMinutes: 28,
      topicsDetected: ['Baggage Claim', 'Lost Item'],
      sentiment: -54,
      summary: 'Bag still missing after seven days. Customer escalated; case left open at chat end.',
    },
    surveySentAt: '2026-06-01T08:00:00Z',
    surveyCompletedAt: '2026-06-01T08:38:00Z',
    status: 'completed',
    csat: 20,
    vu: 50,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate how we have handled your missing bag so far?',
        topic: 'Lost Item',
        min: 1, max: 5,
        response: 1,
      },
      {
        kind: 'open',
        prompt: 'What about how we have handled it has been most frustrating?',
        topic: 'Lost Item',
        generatedFrom: { source: 'interaction', sentiment: -54, topic: 'Lost Item' },
        response: 'It has been seven days. Every time I chat in I get a different person and have to explain from scratch. No one owns my case.',
        responseSentiment: -58,
      },
      {
        kind: 'open',
        prompt: 'What would having someone "own" your case look like?',
        topic: 'Lost Item',
        generatedFrom: { source: 'prior-response', sentiment: -58 },
        response: 'A name. A number to call back. A daily update. Anything that feels like a human is actually looking.',
        responseSentiment: -32,
      },
    ],
  },
  {
    id: 'SR-BCF-005',
    campaignId: 'baggage-claim-followup',
    customer: { name: 'Carla Rossi', phone: '+39 333 456 7890', email: 'c.rossi@example.com' },
    agent: { name: 'Tom H.', id: 'AG-3082' },
    interaction: {
      date: '2026-06-01T10:22:00Z',
      channel: 'AI Agent',
      durationMinutes: 8,
      topicsDetected: ['Baggage Claim', 'Compensation'],
      sentiment: -10,
      summary: 'Customer asked about reimbursement for essentials. AI Agent shared the policy and case reference.',
    },
    surveySentAt: '2026-06-01T17:00:00Z',
    surveyCompletedAt: null,
    status: 'partial',
    csat: 60,
    vu: 33,
    questions: [
      {
        kind: 'rating',
        prompt: 'How clear was the reimbursement policy we shared?',
        topic: 'Compensation',
        min: 1, max: 5,
        response: 3,
      },
      {
        kind: 'open',
        prompt: 'What parts of the policy felt unclear or worth explaining differently?',
        topic: 'Compensation',
        generatedFrom: { source: 'interaction', sentiment: -10, topic: 'Compensation' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'Where would you have wanted to find this policy without having to chat in?',
        topic: 'Compensation',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
  {
    id: 'SR-BCF-006',
    campaignId: 'baggage-claim-followup',
    customer: { name: 'Tom Mitchell', phone: '+44 7700 900 651', email: 't.mitchell@example.com' },
    agent: { name: 'Sara N.', id: 'AG-3151' },
    interaction: {
      date: '2026-05-30T19:05:00Z',
      channel: 'Chat',
      durationMinutes: 17,
      topicsDetected: ['Baggage Claim', 'Damaged Item'],
      sentiment: -38,
      summary: 'Customer reported a damaged suitcase on arrival. Photo evidence shared; claim opened.',
    },
    surveySentAt: '2026-05-31T22:00:00Z',
    surveyCompletedAt: '2026-05-31T22:19:00Z',
    status: 'completed',
    csat: 40,
    vu: 41,
    questions: [
      {
        kind: 'rating',
        prompt: 'How well did we handle your damaged-bag claim?',
        topic: 'Damaged Item',
        min: 1, max: 5,
        response: 2,
      },
      {
        kind: 'open',
        prompt: 'What about the process felt slow or unfair to you?',
        topic: 'Damaged Item',
        generatedFrom: { source: 'interaction', sentiment: -38, topic: 'Damaged Item' },
        response: 'I was asked for photos, then a receipt, then a quote for repair. Every reply meant another wait.',
        responseSentiment: -34,
      },
      {
        kind: 'open',
        prompt: 'Would batching those requests into one have helped?',
        topic: 'Damaged Item',
        generatedFrom: { source: 'prior-response', sentiment: -34 },
        response: 'Yes. Tell me everything you need on day one. I would happily send it once.',
        responseSentiment: -8,
      },
    ],
  },

  /* ============================================================
   * Loyalty Tier Check-in
   * ============================================================ */
  {
    id: 'SR-LTC-001',
    campaignId: 'loyalty-tier-checkin',
    customer: { name: 'David Lee', phone: '+1 415 555 0192', email: 'david.lee@example.com' },
    agent: { name: 'Carlos R.', id: 'AG-4072' },
    interaction: {
      date: '2026-05-27T14:00:00Z',
      channel: 'AI Agent',
      durationMinutes: 7,
      topicsDetected: ['Tier Status', 'Upgrade Request'],
      sentiment: 18,
      summary: 'Customer confirmed eligibility for Gold tier upgrade. AI Agent walked through new benefits.',
    },
    surveySentAt: '2026-05-28T15:00:00Z',
    surveyCompletedAt: '2026-05-28T15:12:00Z',
    status: 'completed',
    csat: 100,
    vu: 30,
    questions: [
      {
        kind: 'rating',
        prompt: 'How well did we explain your new tier benefits?',
        topic: 'Tier Status',
        min: 1, max: 5,
        response: 5,
      },
      {
        kind: 'open',
        prompt: 'Which benefit are you most excited to use first?',
        topic: 'Tier Status',
        generatedFrom: { source: 'interaction', sentiment: 18, topic: 'Tier Status' },
        response: 'The lounge access. I travel monthly and that alone justifies the loyalty.',
        responseSentiment: 38,
      },
      {
        kind: 'open',
        prompt: 'Is there a benefit you would love to see added to your tier?',
        topic: 'Tier Status',
        generatedFrom: { source: 'prior-response', sentiment: 38 },
        response: 'Guest lounge passes would be a great addition. I travel for work but bring family for trips.',
        responseSentiment: 22,
      },
    ],
  },
  {
    id: 'SR-LTC-002',
    campaignId: 'loyalty-tier-checkin',
    customer: { name: 'Sandra Wu', phone: '+852 9123 4567', email: 's.wu@example.com' },
    agent: { name: 'Jennifer T.', id: 'AG-4108' },
    interaction: {
      date: '2026-05-29T09:14:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['Benefits Inquiry'],
      sentiment: 8,
      summary: 'Customer asked which benefits applied on partner airlines. Reply gave full list.',
    },
    surveySentAt: '2026-05-29T17:00:00Z',
    surveyCompletedAt: '2026-05-29T17:22:00Z',
    status: 'completed',
    csat: 80,
    vu: 27,
    questions: [
      {
        kind: 'rating',
        prompt: 'How clear was our answer about your benefits on partner airlines?',
        topic: 'Benefits Inquiry',
        min: 1, max: 5,
        response: 4,
      },
      {
        kind: 'open',
        prompt: 'What part of the answer was most useful for you?',
        topic: 'Benefits Inquiry',
        generatedFrom: { source: 'interaction', sentiment: 8, topic: 'Benefits Inquiry' },
        response: 'The table comparing the two alliances was exactly what I needed. I had been guessing.',
        responseSentiment: 24,
      },
      {
        kind: 'open',
        prompt: 'Where would you have liked to find that comparison without asking?',
        topic: 'Benefits Inquiry',
        generatedFrom: { source: 'prior-response', sentiment: 24 },
        response: 'Inside the app on the loyalty page. Right now I have to scroll through PDFs on the website.',
        responseSentiment: 4,
      },
    ],
  },
  {
    id: 'SR-LTC-003',
    campaignId: 'loyalty-tier-checkin',
    customer: { name: 'Pierre Dubois', phone: '+33 6 12 34 56 78', email: 'p.dubois@example.com' },
    agent: { name: 'Aiko K.', id: 'AG-4135' },
    interaction: {
      date: '2026-05-30T12:40:00Z',
      channel: 'AI Agent',
      durationMinutes: 10,
      topicsDetected: ['Upgrade Request', 'Reward Points'],
      sentiment: -4,
      summary: 'Customer used points to upgrade. Got a value-of-points question that the bot escalated.',
    },
    surveySentAt: '2026-05-31T13:00:00Z',
    surveyCompletedAt: '2026-05-31T13:30:00Z',
    status: 'completed',
    csat: 60,
    vu: 28,
    questions: [
      {
        kind: 'rating',
        prompt: 'How fair did the points-to-upgrade exchange feel?',
        topic: 'Reward Points',
        min: 1, max: 5,
        response: 3,
      },
      {
        kind: 'open',
        prompt: 'What about the points value felt off to you?',
        topic: 'Reward Points',
        generatedFrom: { source: 'interaction', sentiment: -4, topic: 'Reward Points' },
        response: 'The cash price difference between economy and business was £400 but it cost me 35,000 points. That works out worse than just buying it.',
        responseSentiment: -22,
      },
      {
        kind: 'open',
        prompt: 'Would knowing the cash value upfront have changed your decision?',
        topic: 'Reward Points',
        generatedFrom: { source: 'prior-response', sentiment: -22 },
        response: 'Probably yes. I would have saved points for a transatlantic redemption where the value is much better.',
        responseSentiment: -10,
      },
    ],
  },
  {
    id: 'SR-LTC-004',
    campaignId: 'loyalty-tier-checkin',
    customer: { name: 'Anika Sharma', phone: '+91 98 7654 3210', email: 'a.sharma@example.com' },
    agent: { name: 'Carlos R.', id: 'AG-4072' },
    interaction: {
      date: '2026-05-30T16:15:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['Tier Status', 'Membership Renewal'],
      sentiment: 12,
      summary: 'Customer confirmed she had retained Platinum for another year. Renewal acknowledged.',
    },
    surveySentAt: '2026-05-31T10:00:00Z',
    surveyCompletedAt: '2026-05-31T10:14:00Z',
    status: 'completed',
    csat: 80,
    vu: 26,
    questions: [
      {
        kind: 'rating',
        prompt: 'How smoothly did your tier renewal go this year?',
        topic: 'Membership Renewal',
        min: 1, max: 5,
        response: 4,
      },
      {
        kind: 'open',
        prompt: 'What part of the renewal felt easiest?',
        topic: 'Membership Renewal',
        generatedFrom: { source: 'interaction', sentiment: 12, topic: 'Membership Renewal' },
        response: 'Nothing for me to do. The email just confirmed it had auto-renewed. That is exactly what loyalty should feel like.',
        responseSentiment: 28,
      },
      {
        kind: 'open',
        prompt: 'Is there anything you wished felt more recognised at renewal?',
        topic: 'Membership Renewal',
        generatedFrom: { source: 'prior-response', sentiment: 28 },
        response: 'A small thank-you with my next boarding pass would feel personal. Right now I find out via the auto email.',
        responseSentiment: 14,
      },
    ],
  },
  {
    id: 'SR-LTC-005',
    campaignId: 'loyalty-tier-checkin',
    customer: { name: 'George Papadopoulos', phone: '+30 694 123 4567', email: 'g.papa@example.com' },
    agent: { name: 'Jennifer T.', id: 'AG-4108' },
    interaction: {
      date: '2026-06-01T08:50:00Z',
      channel: 'AI Agent',
      durationMinutes: 4,
      topicsDetected: ['Tier Status'],
      sentiment: 2,
      summary: 'Customer checked progress toward next tier. AI Agent showed required activity and timing.',
    },
    surveySentAt: '2026-06-01T20:00:00Z',
    surveyCompletedAt: null,
    status: 'partial',
    csat: 60,
    vu: 24,
    questions: [
      {
        kind: 'rating',
        prompt: 'How clear was the path to the next tier we showed you?',
        topic: 'Tier Status',
        min: 1, max: 5,
        response: 3,
      },
      {
        kind: 'open',
        prompt: 'What about that path could be made clearer or more motivating?',
        topic: 'Tier Status',
        generatedFrom: { source: 'interaction', sentiment: 2, topic: 'Tier Status' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'Would seeing a progress bar in the app help you track it day to day?',
        topic: 'Tier Status',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
  {
    id: 'SR-LTC-006',
    campaignId: 'loyalty-tier-checkin',
    customer: { name: 'Helen Wong', phone: '+1 604 555 0188', email: 'h.wong@example.com' },
    agent: { name: 'Aiko K.', id: 'AG-4135' },
    interaction: {
      date: '2026-05-31T17:25:00Z',
      channel: 'Chat',
      durationMinutes: 19,
      topicsDetected: ['Benefits Inquiry', 'Lounge Access'],
      sentiment: -24,
      summary: 'Customer denied lounge entry due to fare class restriction not flagged at booking.',
    },
    surveySentAt: '2026-06-01T09:00:00Z',
    surveyCompletedAt: '2026-06-01T09:31:00Z',
    status: 'completed',
    csat: 40,
    vu: 35,
    questions: [
      {
        kind: 'rating',
        prompt: 'How did the lounge access experience match your expectations?',
        topic: 'Lounge Access',
        min: 1, max: 5,
        response: 2,
      },
      {
        kind: 'open',
        prompt: 'What about being turned away felt particularly disappointing?',
        topic: 'Lounge Access',
        generatedFrom: { source: 'interaction', sentiment: -24, topic: 'Lounge Access' },
        response: 'The lounge is the entire reason I pay for Platinum. Being turned away because of a fare-class footnote felt like a bait and switch.',
        responseSentiment: -42,
      },
      {
        kind: 'open',
        prompt: 'When in the journey should that restriction have been flagged to you?',
        topic: 'Lounge Access',
        generatedFrom: { source: 'prior-response', sentiment: -42 },
        response: 'At booking. The fare picker should say up front that this fare does not include lounge access for my tier.',
        responseSentiment: -18,
      },
    ],
  },

  /* ============================================================
   * General Inquiry Pulse
   * ============================================================ */
  {
    id: 'SR-GIP-001',
    campaignId: 'general-inquiry-pulse',
    customer: { name: 'Brian Coyle', phone: '+353 87 234 5678', email: 'b.coyle@example.com' },
    agent: { name: 'Sam W.', id: 'AG-5021' },
    interaction: {
      date: '2026-05-28T11:42:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['General Inquiry', 'Account Status'],
      sentiment: 0,
      summary: 'Customer asked to merge two accounts. Reply confirmed it had been actioned.',
    },
    surveySentAt: '2026-05-29T08:00:00Z',
    surveyCompletedAt: '2026-05-29T08:18:00Z',
    status: 'completed',
    csat: 60,
    vu: 22,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate our handling of your account merge?',
        topic: 'Account Status',
        min: 1, max: 5,
        response: 3,
      },
      {
        kind: 'open',
        prompt: 'What was the experience like end-to-end for you?',
        topic: 'Account Status',
        generatedFrom: { source: 'interaction', sentiment: 0, topic: 'Account Status' },
        response: 'It was fine. Took a few emails but the second-tier team got it done.',
        responseSentiment: 4,
      },
      {
        kind: 'open',
        prompt: 'Is there anything that would have made it less "fine" and more positive?',
        topic: 'Account Status',
        generatedFrom: { source: 'prior-response', sentiment: 4 },
        response: 'Doing it in one reply instead of three. I had to keep re-explaining who I was.',
        responseSentiment: -6,
      },
    ],
  },
  {
    id: 'SR-GIP-002',
    campaignId: 'general-inquiry-pulse',
    customer: { name: 'Lena Schmidt', phone: '+49 173 555 8821', email: 'l.schmidt@example.com' },
    agent: { name: 'Lily B.', id: 'AG-5054' },
    interaction: {
      date: '2026-05-30T13:20:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['General Inquiry'],
      sentiment: -8,
      summary: 'Customer asked about service hours for a specific destination.',
    },
    surveySentAt: '2026-05-31T09:00:00Z',
    surveyCompletedAt: null,
    status: 'abandoned',
    csat: null,
    vu: 19,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate the answer you received about service hours?',
        topic: 'Service Hours',
        min: 1, max: 5,
        response: null,
      },
      {
        kind: 'open',
        prompt: 'What about the response felt incomplete or hard to use?',
        topic: 'Service Hours',
        generatedFrom: { source: 'interaction', sentiment: -8, topic: 'Service Hours' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'Where would you have preferred to find that information directly?',
        topic: 'Service Hours',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
  {
    id: 'SR-GIP-003',
    campaignId: 'general-inquiry-pulse',
    customer: { name: 'Anthony Russo', phone: '+39 347 234 5678', email: 'a.russo@example.com' },
    agent: { name: 'Sam W.', id: 'AG-5021' },
    interaction: {
      date: '2026-05-31T15:40:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['Pricing', 'Policy Question'],
      sentiment: -18,
      summary: 'Customer challenged a pricing change on his booking. Reply explained the fare rule.',
    },
    surveySentAt: '2026-06-01T11:00:00Z',
    surveyCompletedAt: null,
    status: 'partial',
    csat: 40,
    vu: 26,
    questions: [
      {
        kind: 'rating',
        prompt: 'How well did we explain the fare change on your booking?',
        topic: 'Pricing',
        min: 1, max: 5,
        response: 2,
      },
      {
        kind: 'open',
        prompt: 'What about the explanation didn\'t address your concern?',
        topic: 'Pricing',
        generatedFrom: { source: 'interaction', sentiment: -18, topic: 'Pricing' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'How should pricing changes be communicated before they happen?',
        topic: 'Pricing',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
  {
    id: 'SR-GIP-004',
    campaignId: 'general-inquiry-pulse',
    customer: { name: 'Mia Chen', phone: '+1 212 555 0156', email: 'm.chen@example.com' },
    agent: { name: 'Lily B.', id: 'AG-5054' },
    interaction: {
      date: '2026-05-30T17:08:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['Booking Change'],
      sentiment: 6,
      summary: 'Customer requested a name correction. Resolved in a single reply.',
    },
    surveySentAt: '2026-05-31T13:00:00Z',
    surveyCompletedAt: '2026-05-31T13:22:00Z',
    status: 'completed',
    csat: 80,
    vu: 21,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate how quickly we corrected your booking?',
        topic: 'Booking Change',
        min: 1, max: 5,
        response: 4,
      },
      {
        kind: 'open',
        prompt: 'What worked well about the correction process?',
        topic: 'Booking Change',
        generatedFrom: { source: 'interaction', sentiment: 6, topic: 'Booking Change' },
        response: 'Single email, single reply. No call needed.',
        responseSentiment: 22,
      },
      {
        kind: 'open',
        prompt: 'Would you have wanted to make this change yourself online?',
        topic: 'Booking Change',
        generatedFrom: { source: 'prior-response', sentiment: 22 },
        response: 'Yes for typos. But I get why bigger changes need an agent.',
        responseSentiment: 8,
      },
    ],
  },
  {
    id: 'SR-GIP-005',
    campaignId: 'general-inquiry-pulse',
    customer: { name: 'Kevin Park', phone: '+82 10 1234 5678', email: 'k.park@example.com' },
    agent: { name: 'Sam W.', id: 'AG-5021' },
    interaction: {
      date: '2026-05-30T08:30:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['Pricing', 'Policy Question'],
      sentiment: -42,
      summary: 'Customer felt a refund policy was unclear. Reply explained but did not change the policy.',
    },
    surveySentAt: '2026-05-31T11:00:00Z',
    surveyCompletedAt: '2026-05-31T11:28:00Z',
    status: 'completed',
    csat: 20,
    vu: 30,
    questions: [
      {
        kind: 'rating',
        prompt: 'How well did we resolve your pricing concern?',
        topic: 'Policy Question',
        min: 1, max: 5,
        response: 1,
      },
      {
        kind: 'open',
        prompt: 'What about the resolution felt unsatisfying?',
        topic: 'Policy Question',
        generatedFrom: { source: 'interaction', sentiment: -42, topic: 'Policy Question' },
        response: 'You quoted the policy back at me. That is not a resolution. I wanted to understand why the policy exists, not be told it does.',
        responseSentiment: -50,
      },
      {
        kind: 'open',
        prompt: 'What would have made the answer feel like a real explanation?',
        topic: 'Policy Question',
        generatedFrom: { source: 'prior-response', sentiment: -50 },
        response: 'Tell me the reasoning. "We don\'t refund within 24 hours because…" That is a conversation. A policy quote is not.',
        responseSentiment: -22,
      },
    ],
  },
  {
    id: 'SR-GIP-006',
    campaignId: 'general-inquiry-pulse',
    customer: { name: 'Fiona Walsh', phone: '+353 86 123 4567', email: 'f.walsh@example.com' },
    agent: { name: 'Lily B.', id: 'AG-5054' },
    interaction: {
      date: '2026-06-01T14:55:00Z',
      channel: 'Email',
      durationMinutes: 0,
      topicsDetected: ['General Inquiry'],
      sentiment: -2,
      summary: 'Customer asked about luggage allowance. Reply sent the same day.',
    },
    surveySentAt: '2026-06-02T08:00:00Z',
    surveyCompletedAt: null,
    status: 'pending',
    csat: null,
    vu: 20,
    questions: [
      {
        kind: 'rating',
        prompt: 'How would you rate our answer about your luggage allowance?',
        topic: 'General Inquiry',
        min: 1, max: 5,
        response: null,
      },
      {
        kind: 'open',
        prompt: 'What about the answer was most useful or unclear?',
        topic: 'General Inquiry',
        generatedFrom: { source: 'interaction', sentiment: -2, topic: 'General Inquiry' },
        response: null,
        responseSentiment: null,
      },
      {
        kind: 'open',
        prompt: 'Where would you have wanted to find this directly?',
        topic: 'General Inquiry',
        generatedFrom: { source: 'prior-response', sentiment: 0 },
        response: null,
        responseSentiment: null,
      },
    ],
  },
]

export function getSurveysForCampaign(campaignId: string): Survey[] {
  return SURVEYS.filter(s => s.campaignId === campaignId)
}

export function getSurveyById(id: string): Survey | undefined {
  return SURVEYS.find(s => s.id === id)
}
